import { useTheme } from "hooks/theme";
import Head from "next/head";
import Image from "next/image";
import type { ReactNode } from "react";

interface Props {
  children: ReactNode;
  styles: {
    readonly [key: string]: string;
  };
}

export default function Layout({ children, styles }: Props) {
  const { theme } = useTheme();

  return (
    <div className={`${styles[theme]} ${theme}`}>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className={styles.main}>{children}</main>
        <footer className={styles.footer}>
          <a
            href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            target="_blank"
            rel="noopener noreferrer"
          >
            Powered by{" "}
            <span className={styles.logo}>
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                width={72}
                height={16}
              />
            </span>
          </a>
        </footer>
      </div>
    </div>
  );
}
